config/routes.rb
Rails.application.routes.draw do
  resources :properties
  resources :stations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :stations, dependent: :destroy
    accepts_nested_attributes_for :stations, allow_destroy: true, reject_if: :all_blank

    validates :name, :rent, :adress, :building, :remarks, presence: true
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    @property.stations.new
    @property.stations.new
  end

  # GET /properties/1/edit
  def edit
    @property.stations.new
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :rent, :adress, :building, :remarks, stations_attributes: [:id, :railway, :name, :minute])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
    before_action :set_station, only: %i[ show edit update destroy ]

  # GET /stations or /stations.json
  def index
    @stations = station.all
  end

  # GET /stations/1 or /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations or /stations.json
  def create
    @station = station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: "station was successfully created." }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1 or /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: "station was successfully updated." }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1 or /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: "station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = station.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def station_params
      params.require(:station).permit(:railway, :name, :minutes, :property_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiveMofmof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.number_field :rent %> <span>RWF</span>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_area :adress %>
  </div>

  <div class="field">
    <%= form.label :building_age %>
    <%= form.number_field :building %> <span>year/years old</span>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

<hr>
  <%= form.fields_for :stations do |form| %>
    <h2>Name of railway line <%= form.index + 1 %></h2>

    <div class="field">
      <%= form.label :Name_of_railway_line %>
      <%= form.text_field :railway %>
    </div>

    <div class="field">
      <%= form.label :Station_name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :How_many_minutes_walk %>
      <%= form.number_field :minutes %> <span>min/mins</span>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Adress</th>
      <th>Building age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.rent %></td>
        <td><%= property.adress %></td>
        <td><%= property.building %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @property.adress %>
</p>

<p>
  <strong>Building age:</strong>
  <%= @property.building %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @property.remarks %>
</p>

<% @property.stations.each_with_index do |r, i| %>
<hr>
<% if r.railway.present?  %>
<h2>Nearest station <%= i+1 %></h2>
<p>
  <strong>Name of railway:</strong>
  <%= r.railway %>
</p>
<p>
  <strong>Station name:</strong>
  <%= r.name %>
</p>
<p>
  <strong>How many minutes walk:</strong>
  <%= r.minutes %> min/mins
</p>
<% end %>
<% end %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>